### ISSUE TITLE
Have a way to have global settings

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/cheeto#14]
Adam Getchell wants **all** Farm users to have access to the `gpul` partition, so we need a way to merge in (splat*) per-cluster global settings.

My first thought is `domains/farm.hpc.ucdavis.edu/ALL.yaml` with contents similar to
```
group:
  ALL:
    slurm:
      partitions:
        gpul:
          qos:
            priority: 0
```

Then this gets merged into the `merged/all.yaml` file for every user.
