### ISSUE TITLE
Allow a boolean for globus being enabled per PI share

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/cheeto#15]
I am about to dig into creating a Puppet module for creating Globus shares. I believe we will need this added to cheeto's schema validation. I was picturing something like `globus: true` in the share definition:
```
group:
  awetzelgrp:
    storage:

      - name: awetzelroot
        owner: root
        group: root
        zfs:
          quota: 400T
        autofs:
          nas: waltz
          path: /waltz/share/wetzellab

      - name: awetzelgrp
        owner: awetzel
        group: awetzelgrp
        zfs: false
        globus: true
        autofs:
          nas: waltz
          path: /waltz/share/wetzellab/group
```
